Description of hill
Home > nca > nca_auxiliary > hill_kinetics > hill.m
hill
PURPOSE
SYNOPSIS
function y = hill(x,ymax,km,hc)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
hill_msr
display_module_result
plot_true_versus_fit plot_true_versus_fit(X,X_pred,W,indices,siz)