Description of hill_msr
Home > nca > nca_auxiliary > hill_kinetics > hill_msr.m
hill_msr
PURPOSE
SYNOPSIS
function msr = hill_msr(kpar,x,y)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
hill
This function is called by:
display_module_result
plot_true_versus_fit plot_true_versus_fit(X,X_pred,W,indices,siz)