Description of make_W_identifiable
Home > nca > nca_functions > make_W_identifiable.m
make_W_identifiable
PURPOSE
[Wblock,genes_kept,TF_removed,genes_removed] = make_W_identifiable(W,gene_indices_choice,TF_indices_choice, general)
SYNOPSIS
function [Wblock,genes_kept,TF_removed,genes_removed] = make_W_identifiable(W,gene_indices_choice,TF_indices_choice, general)
DESCRIPTION
 [Wblock,genes_kept,TF_removed,genes_removed] =  make_W_identifiable(W,gene_indices_choice,TF_indices_choice, general)
 extract identifiable TF subnetwork from given network
 only argument W is required
CROSS-REFERENCE INFORMATION
This function calls:
nca_identifiability [error_flag,independent_TF,dependent_TF,T,violating_columns,dependent_columns] = nca_identifiability(A_true,B_true)
This function is called by:
prepare_data_block prepare_data_block(filename,identifiable_flag,TF_list,gene_list)
nca_artificial_data [W_true,A_true,B_true,X,X_true] = nca_artificial_data(n_TF,n_genes,n_timepoints,ptot,sigma)