Description of modify_network
Home > nca > nca_functions > modify_network.m
modify_network
PURPOSE
SYNOPSIS
function [A_opt,B_opt,W_opt,X_opt,X_error_opt,changes] = modify_network(A,B,W,X,X_error,method,parameters,general,lambda_dep,regularise_flag);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)
modify_signs [W_new,A,B,changes,X_pred] = relax_signs(X,W,B,W_signs,p_sign_error,verbose)
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
optimise_W [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);
This function is called by: