Description of modify_signs
Home > nca > nca_functions > modify_signs.m
modify_signs
PURPOSE
[W_new,A,B,changes,X_pred] = relax_signs(X,W,B,W_signs,p_sign_error,verbose)
SYNOPSIS
function [W_new,A_new,changes,X_pred] = modify_signs(X,W,A,B,W_signs,X_error,p_sign_error,fixed_TF,verbose,general,lambda_dep,regularise_flag)
DESCRIPTION
 [W_new,A,B,changes,X_pred] = relax_signs(X,W,B,W_signs,p_sign_error,verbose)
 updates the sign restrictions in W based on a matrix of (supposedly) known signs
 and an error probability.
 Note that the matrix B is kept constant during the optimisation!
CROSS-REFERENCE INFORMATION
This function calls:
num2bit
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
This function is called by:
modify_network