Description of modify_shifts
Home > nca > nca_functions > modify_shifts.m
modify_shifts
PURPOSE
[X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)
SYNOPSIS
function [X_shifted,shifts,A_new,X_error_shifted] = modify_shifts(W,X,A,B,sigma_prior,sigma_loglike,X_error,experiments)
DESCRIPTION
 [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)
CROSS-REFERENCE INFORMATION
This function calls:
fill_nan
shift_matrix MM = shift_matrix(M,s)
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
This function is called by:
modify_network
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)