Description of modify_connections
Home > nca > nca_functions > modify_connections.m
modify_connections
PURPOSE
W_new = choose_new_W(X,W,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,verbose)
SYNOPSIS
function W_new = modify_connections(X,W,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,verbose,general,lambda_dep,regularise_flag)
DESCRIPTION
 W_new = choose_new_W(X,W,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,verbose)
 n_threshold_possible: maximal number of inputs per gene up to which all combinations are checked
 sigma_0: estimated std dev of measurements
 P prior probabilities of for non-zero element of W.data
 p_sign_error: prior probability of a wrong sign in W.signs
CROSS-REFERENCE INFORMATION
This function calls:
num2bit
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
This function is called by:
optimise_W [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);