Description of nca_loop
Home > nca > nca_functions > nca_loop.m
nca_loop
PURPOSE
[A_list,B_list] = nca_loop(...
SYNOPSIS
function [A_list,B_list] = nca_loop(X,W_data,W_signs,graphics_flag,verbose,force_B1,initial_choice,n_itmax,lambda,lambda_A,lambda_B,A_first,B_first,repeat,epsilon,no_nans,nan_blocks,TF_names,general,lambda_dep,regularise_flag,no_nan_predictions,n_processes,random_seed,repeat_noise_std)
DESCRIPTION
 [A_list,B_list] = nca_loop(...
    X,W_data,W_signs,graphics_flag,verbose,force_B1,initial_choice,...
    n_itmax,lambda,lambda_A,lambda_B,A_first,B_first,repeat,epsilon,...
    no_nans,nan_blocks,TF_names,general,lambda_dep,regularise_flag,...
    no_nan_predictions,n_processes,random_seed,repeat_noise_std)
 explanation of arguments: see nca.m
CROSS-REFERENCE INFORMATION
This function calls:
nca_goal
nca_rescale [A,B] = nca_rescale(A,B,force_B1)
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
optimise_B_given_A B_new = optimise_B_given_A(X,Wdata,A,lambda_B,force_B1,no_nans,blocks)
im im(X,m,rownames,colnames)
This function is called by: