Description of optimise_B_given_A
Home > nca > nca_functions > optimise_B_given_A.m
optimise_B_given_A
PURPOSE
B_new = optimise_B_given_A(X,Wdata,A,lambda_B,force_B1,no_nans,blocks)
SYNOPSIS
function B_new = optimise_B_given_A(X,Wdata,A,lambda_A,lambda_B,force_B1,no_nans,blocks,B,general,lambda_dep,regularise_flag)
DESCRIPTION
 B_new = optimise_B_given_A(X,Wdata,A,lambda_B,force_B1,no_nans,blocks)
 X is allowed to contain nans, in a controlled manner:
 presence of nans must be indicated by no_nans = 0, and the data must come in blocks (time series)
 blocks{i} contains the indices of the time points belonging to the ith block
 within each block holds: a gene that contains at least one nan value is considered
 unmeasured.
CROSS-REFERENCE INFORMATION
This function calls:
nca_goal
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
nca_loop [A_list,B_list] = nca_loop(...