Description of optimise_A_given_B
Home > nca > nca_functions > optimise_A_given_B.m
optimise_A_given_B
PURPOSE
A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
SYNOPSIS
function A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag,lambda_B)
DESCRIPTION
 A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
if ~exist('signs','var'),      signs       = []; end
if ~exist('general','var'),    general     = []; end
if ~exist('lambda_dep','var'), lambda_dep  = 1;  end
CROSS-REFERENCE INFORMATION
This function calls:
my_lsqlin don't forget to addpath ~/matlab_packages/minq
This function is called by:
modify_connections W_new = choose_new_W(X,W,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,verbose)
modify_network
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)
modify_signs [W_new,A,B,changes,X_pred] = relax_signs(X,W,B,W_signs,p_sign_error,verbose)
nca_loop [A_list,B_list] = nca_loop(...
nca_make_info
optimise_W [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);
display_input_weights -----------------------------------------------------------