Description of optimise_W
Home > nca > nca_functions > optimise_W.m
optimise_W
PURPOSE
[W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);
SYNOPSIS
function [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose,general,lambda_dep,regularise_flag);
DESCRIPTION
 [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);
 Iterate over the adaptation of W_new and A,B
CROSS-REFERENCE INFORMATION
This function calls:
modify_connections W_new = choose_new_W(X,W,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,verbose)
optimise_A_given_B A_new = optimise_A_given_B(X,Wdata,B,signs,lambda_A,A,general,lambda_dep,regularise_flag)
im im(X,m,rownames,colnames)
This function is called by:
modify_network