Description of minq
Home > minq > minq.m
minq
PURPOSE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SYNOPSIS
function [x,fct,ier,nsub]=minq(gam,c,G,xu,xo,prt,xx);
DESCRIPTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% minq.m %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 function [x,fct,ier,nsub]=minq(gam,c,G,xu,xo,prt,xx);
 minimizes an affine quadratic form subject to simple bounds,
 using coordinate searches and reduced subspace minimizations
 using LDL^T factorization updates
    min    fct = gam + c^T x + 0.5 x^T G x
    s.t.   x in [xu,xo]    % xu<=xo is assumed
 where G is a symmetric n x n matrix, not necessarily definite
 (if G is indefinite, only a local minimum is found)
 if G is sparse, it is assumed that the ordering is such that
 a sparse modified Cholesky factorization is feasible
 prt    printlevel
 xx    initial guess (optional)
 x    minimizer (but unbounded direction if ier=1)
 fct    optimal function value
 ier    0  (local minimizer found)
     1  (unbounded below)
     99 (maxit exceeded)
 calls getalp.m, ldl*.m, minqsub.m, pr01.m
CROSS-REFERENCE INFORMATION
This function calls:
getalp %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
minqsub %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pr01 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
This function is called by:
minqdef %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
minqsep %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rls %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
my_lsqlin don't forget to addpath ~/matlab_packages/minq