Description of cd_data
Home > nca > nca_auxiliary > cd_data.m
cd_data
PURPOSE
cd_data(filename,type);
SYNOPSIS
function cd_data(filename,type);
DESCRIPTION
 cd_data(filename,type);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
care_for_unmatched_genes Combine all data that form an identifiable network
make_X_matrices make_X_matrices(network_name,data_name);
match_experiment_and_network match_experiment_and_network(network_name,data_name,version_name);
prepare_data_block prepare_data_block(filename,identifiable_flag,TF_list,gene_list)