Description of fill_nan
Home > nca > nca_auxiliary > fill_nan.m
fill_nan
PURPOSE
SYNOPSIS
function M= fill_nan(M)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
local_time_shift
care_for_unmatched_genes Combine all data that form an identifiable network
preprocess_gfp_data function [DD,info] = preprocess_gfp_data(D,parameters)
make_X_matrices make_X_matrices(network_name,data_name);
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)