Description of shift_matrix
Home > nca > nca_auxiliary > shift_matrix.m
shift_matrix
PURPOSE
MM = shift_matrix(M,s)
SYNOPSIS
function MM = shift_matrix(M,s)
DESCRIPTION
 MM = shift_matrix(M,s)
 shift values in matrix by s columns to the right
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gfp_data_estimate_error [est,est1,est2] = gfp_data_estimate_error(data,use_time_points,mean_cv);
gfp_data_unify_genes DD = gfp_data_unify_genes(D);
preprocess_gfp_data function [DD,info] = preprocess_gfp_data(D,parameters)
modify_shifts [X_shifted,shifts] = modify_shifts(W,X,B,sigma_prior,sigma_loglike)