Description of care_for_unmatched_genes
Home > nca > nca_expression > care_for_unmatched_genes.m
care_for_unmatched_genes
PURPOSE
Combine all data that form an identifiable network
SYNOPSIS
function care_for_unmatched_genes(filename,TF_list,gene_list,A,sigma_flag)
DESCRIPTION
 Combine all data that form an identifiable network
 with all data that do not at all match the regDB network
 prepare the data structure D and according network structures describing the
 known and putative binding sites
CROSS-REFERENCE INFORMATION
This function calls:
cd_data cd_data(filename,type);
fill_nan
choose_from_D D = choose_from_D(D,indices)
choose_from_W W = choose_from_W(W,l_gene,lTF)
combine_D_and_W [D,W,W_picture,D_unmatched] = combine_D_and_W(D,W)
combine_networks [W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by: