Description of combine_D_and_W
Home > nca > nca_expression > combine_D_and_W.m
combine_D_and_W
PURPOSE
[D,W,W_picture,D_unmatched] = combine_D_and_W(D,W)
SYNOPSIS
function [D_comb,W_comb,W_picture,D_unmatched] = combine_D_and_W(D,W)
DESCRIPTION
 [D,W,W_picture,D_unmatched] = combine_D_and_W(D,W)
 Combine experimental data in D with network in W
 according to the GENE NAMES!!!
CROSS-REFERENCE INFORMATION
This function calls:
choose_from_D D = choose_from_D(D,indices)
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
This function is called by:
care_for_unmatched_genes Combine all data that form an identifiable network
match_experiment_and_network match_experiment_and_network(network_name,data_name,version_name);