Description of prepare_data_block
Home > nca > nca_expression > prepare_data_block.m
prepare_data_block
PURPOSE
prepare_data_block(filename,identifiable_flag,TF_list,gene_list)
SYNOPSIS
function [D,W,TF_removed,gene_indices_choice] = prepare_data_block(filename,identifiable_flag,TF_list,gene_list)
DESCRIPTION
 prepare_data_block(filename,identifiable_flag,TF_list,gene_list)
 choose a part of the whole data, display and save them
CROSS-REFERENCE INFORMATION
This function calls:
cd_data cd_data(filename,type);
choose_from_D D = choose_from_D(D,indices)
reorder_genes_W_D [W,D] = reorder_genes_W_D(gene_list,TF_list,W,D)
make_W_identifiable [Wblock,genes_kept,TF_removed,genes_removed] = make_W_identifiable(W,gene_indices_choice,TF_indices_choice, general)
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
This function is called by: