Description of D_display
Home > nca > nca_graphics > D_display.m
D_display
PURPOSE
[GFP_p_OD,GFPder_p_OD,OD,GFP] = D_display(D,Wblock,graphics_flag)
SYNOPSIS
function [GFP_p_OD,GFPder_p_OD,OD,GFP] = D_display(D,Wblock,graphics_flag)
DESCRIPTION
 [GFP_p_OD,GFPder_p_OD,OD,GFP] = D_display(D,Wblock,graphics_flag)
 choose
CROSS-REFERENCE INFORMATION
This function calls:
normleft_max
find_operon
im im(X,m,rownames,colnames)
This function is called by: