Description of display_curves_and_connectivity
Home > nca > nca_graphics > display_curves_and_connectivity.m
display_curves_and_connectivity
PURPOSE
display_curves_and_connectivity(W,X,TF_act,X_additional,options,arrow_values);
SYNOPSIS
function options = display_curves_and_connectivity(W,X,TF_act,X_additional,options,arrow_values);
DESCRIPTION
 display_curves_and_connectivity(W,X,TF_act,X_additional,options,arrow_values);
options_default = struct('arrow_numbers',1,'implot',0,'lw',1,'net_ratio',0.3,'box_ratio', 0.25,'textyoffset',-0.25);
CROSS-REFERENCE INFORMATION
This function calls:
W_display [pos_TF,pos_operon] = W_display(W,method,options)
BEcolor
rb_colors
This function is called by:
demo_nca -----------------------------------------------
display_module_result