Description of result_curves
Home > nca > nca_graphics > result_curves.m
result_curves
PURPOSE
result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);
SYNOPSIS
function result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);
DESCRIPTION
 result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);
CROSS-REFERENCE INFORMATION
This function calls:
W_display [pos_TF,pos_operon] = W_display(W,method,options)
noticks
subplot_n
This function is called by: