Description of W_display
Home > nca > nca_graphics > W_display.m
W_display
PURPOSE
[pos_TF,pos_operon] = W_display(W,method,options)
SYNOPSIS
function [pos_TF,pos_operon] = W_display(W,method,options)
DESCRIPTION
 [pos_TF,pos_operon] = W_display(W,method,options)
 Display a transcriptional network
 if method = 'N' -> matrix representation (including signs)
 if method = 'M' -> matrix representation (no signs)
 if method = 'R' -> matrix representation (no signs) without names
 otherwise: network representation
 fields of 'options' contain the graphics parameters
 'arrow_numbers',0
 'textsize',11
 'blocks',1
 'xTF',0  %  arrows x value left
 'xOP',1  %  arrows x value right ; % the y values range from 1 to # operons
 'net_width', 1 overrides xOP: xOP is set to xTF + net_width
 'lw',1
 'arrow_values',[]
 'names','genes'
 'textyoffset',0
 'textTFxoffset',0
 'textOPxoffset',0;
 'position' [0.1 0.1 0.85 0.8]
CROSS-REFERENCE INFORMATION
This function calls:
nca_network_support determine those connections in network W that are in addition supported by network W_support
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
find_separate_subgraphs
im im(X,m,rownames,colnames)
my_colors aus read_colors.pl
my_xticklabel
rb_colors
This function is called by:
W_display_operons W_display_operons(W,operons)
display_curves_and_connectivity display_curves_and_connectivity(W,X,TF_act,X_additional,options,arrow_values);
result_curves result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);