Description of combine_networks
Home > nca > nca_networks > combine_networks.m
combine_networks
PURPOSE
[W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
SYNOPSIS
function [W2,Wp2,W_combi] = combine_networks(W,Wp,TF_rename_list,operon_rename_list,n_min,add_TF)
DESCRIPTION
 [W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
 Add entries from network W2 to W1.
 Compare the operons according to the field operon_names.
 Replace TF_names and operon_names in W2 according to TF_rename_list,operon_rename_list
 the pairs in these lists correspond to the names in W1 and W2, respectively.
 the names according to W1 are kept.
 match differing TF names according to rename_list
 (gene names are supposed to be from the same dictionary)
CROSS-REFERENCE INFORMATION
This function calls:
find_TF index = find_TF(TF,D)
find_operon
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
care_for_unmatched_genes Combine all data that form an identifiable network