Description of find_operon
Home > nca > nca_networks > find_operon.m
find_operon
PURPOSE
SYNOPSIS
function index = find_operon(operon,D)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
D_display [GFP_p_OD,GFPder_p_OD,OD,GFP] = D_display(D,Wblock,graphics_flag)
W_display_operons W_display_operons(W,operons)
X_display
combine_networks [W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
operon_regulators t = operon_regulators(operon,W)
pick_subW_operons [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_operons(W,operon_list,sorting)