Description of find_TF
Home > nca > nca_networks > find_TF.m
find_TF
PURPOSE
index = find_TF(TF,D)
SYNOPSIS
function index = find_TF(TF,D)
DESCRIPTION
 index = find_TF(TF,D)
CROSS-REFERENCE INFORMATION
This function calls:
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
check_signs
B_display
combine_networks [W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
pick_subW_TF [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_TF(W,TFlist,sorting,omit)
target_genes t = target_genes(TF,W)
target_operons t = targets(TF,W)