Description of pick_subW_TF
Home > nca > nca_networks > pick_subW_TF.m
pick_subW_TF
PURPOSE
[Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_TF(W,TFlist,sorting,omit)
SYNOPSIS
function [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_TF(W,TFlist,sorting,omit)
DESCRIPTION
 [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_TF(W,TFlist,sorting,omit)
CROSS-REFERENCE INFORMATION
This function calls:
find_TF index = find_TF(TF,D)
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
This function is called by:
W_display_operons W_display_operons(W,operons)
display_module_result