Description of sort_block
Home > nca > nca_networks > sort_block.m
sort_block
PURPOSE
SYNOPSIS
function [p,q] = sort_block(M,only_rows,nit)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
sort_block
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
traveling_salesman p = traveling_salesman(data,nit,method,seed)
This function is called by:
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
sort_block