Description of sort_W_matrix
Home > nca > nca_networks > sort_W_matrix.m
sort_W_matrix
PURPOSE
[W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
SYNOPSIS
function [W, gene_order, TF_order, Wpicture] = sort_W_matrix(W,only_rows)
DESCRIPTION
 [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
 reorder genes and TF in order to get a nice "almost blockdiagonal" matrix
CROSS-REFERENCE INFORMATION
This function calls:
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
sort_block
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
find_separate_subgraphs
This function is called by:
combine_D_and_W [D,W,W_picture,D_unmatched] = combine_D_and_W(D,W)
prepare_data_block prepare_data_block(filename,identifiable_flag,TF_list,gene_list)
pick_subW_TF [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_TF(W,TFlist,sorting,omit)
pick_subW_genes [Wsub,gene_indices,TF_indices,Wpicture] = pick_subW_genes(W,gene_list,sorting)
pick_subW_operons [Wsub,operon_indices,TF_indices,Wpicture] = pick_subW_operons(W,operon_list,sorting)
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)