Description of preprocess_gfp_data
Home > nca > nca_expression > gfp_data > preprocess_gfp_data.m
preprocess_gfp_data
PURPOSE
function [DD,info] = preprocess_gfp_data(D,parameters)
SYNOPSIS
function [DD,info] = preprocess_gfp_data(D, s1, v1, s2, v2, s3, v3,s4, v4, s5, v5, s6, v6, s7, v7, s8, v8,s9, v9, s10, v10, s11, v11, s12, v12,s13, v13, s14, v14, s15, v15)
DESCRIPTION
function [DD,info] = preprocess_gfp_data(D,parameters)
preprocess time curves from gfp reporter experiments
INPUTS
 D  structure with fields
 .gene_names         column list of strings
 .GFP                matrix of gfp fluorescence values, each gene is a row
 .OD                 matrix of optical density values, each gene is a row
 .gene_annotations   (optional field) column list of strings
 parameters (list of parameter names, each followed by the respective value):
  'graphics_flag'       flag: show graphics? (default 0 =no)
  'remove_genes_flag'   flag: removes genes with suspicious data? (default 1 =yes)
  'use_time_points'     vector, indices of time points that should be used
                        (default: all timepoints starting from point 21)
  'max_shift'           maximal time shift allowed for OD alignment (default 20)
  'smoothing_window'    window size for cubic smoothing of time curves (default 20)
  'unique_genes'        flag: should genes with the same name be averaged over? (default 1 =yes)
  'tmin', 'tmax'        indices of data points between which the curves are to be matched
                        (indices within the original data set, not use_time_points, default 10,50)
  'match_what'          'growth_rate','OD' (default 'growth_rate');
OUTPUTS
 DD  structure containing the preprocessed data with fields
 .gene_names          gene names as provided by the input
 .GFP_p_OD            shifted + smoothed GFP/OD
 .GFPder_p_OD         shifted + smoothed (dGFP/dt)/OD
 .GFPder_p_OD_Std_err (rough!!) estimate of the errors in .GFPder_p_OD
 .GFP_shifted         shifted version of GFP curves
 .OD_shifted          shifted version of OD curves
 .growth_rate         shifted version of (dOD/dt)/OD curves
 .gene_annotations    (if no annotations were provided -> contains the gene names)
 .original_indices    vector of gene indices in the original data
 .shifts              vector of time shifts applied to the curves
 info  structure containing additional information with fields
  .no_increasing_OD     index vector denoting genes with decreasing OD
  .no_small_shift           index vector denoting genes with extreme required time shift
  .no_increasing_GFP    index vector denoting genes with decreasing GFP
  .no_considerable_gfp  index vector denoting genes with low GFP
  .mean_OD              mean OD curve
  .scale                scaling factors for OD curves (for the alignment)
USAGE EXAMPLE
 D.GFP        = gfp;
 D.OD         = od;
 D.gene_names = gene_names;
 [DD,info] = preprocess_gfp_data(D);
% or, with some parameters,
 [DD,info] = preprocess_gfp_data(D,'graphics_flag',0,'use_time_points',21:size(D.OD,2));
WHAT THE SCRIPT ACTUALLY DOES:
 1. determine a time shift for each OD curve, such that, in combination with an optimal
    rescaling (determined seperately for each curve), the curve matches optimally the
    median of all curves between tmin (default 10) and tmax (default 50)
 2. Determine suspicious genes fulfilling at least one out of the four criteria mentioned
    in the explanation of .info above
 3. Remove them if this is indicated by the flag 'remove_genes'
 4. Compute smoothed versions and smoothed derivatives of OD and GFP curves (by using
    'smooth_derivative.m'. Shift them according to the time shift determined in (1.)
    and compute GFP/OD and (dGFP/t)/OD
 5. Compute error estimates of (dGFP/t)/OD (see the script 'gfp_data_estimate_error')
 6. Average over repeated occurrences of genes (see the script 'gfp_data_unify_genes')
    if this is indicated by the flag 'unique_genes'
CROSS-REFERENCE INFORMATION
This function calls:
fill_nan
shift_matrix MM = shift_matrix(M,s)
smooth_derivative [y_derivative,y_smoothed] = smooth_derivative(y,n_window,method,x)
transform_OD_timecourse [shift_opt,scale_opt,x_transformed,gfp_transformed] = transform_OD_timecourse(x,x_std,gfp,max_shift);
gfp_data_determine_CV
gfp_data_estimate_error [est,est1,est2] = gfp_data_estimate_error(data,use_time_points,mean_cv);
gfp_data_unify_genes DD = gfp_data_unify_genes(D);
im im(X,m,rownames,colnames)
my_bfilt r = my_bfilt(data)
my_corrcoef [c, pvalue_one_tailed, pvalue_two_tailed] = my_corrcoef(A,B)
This function is called by: