Description of default
Home > nca > utils > default.m
default
PURPOSE
commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
SYNOPSIS
function commandstring = default(varargin)
DESCRIPTION
 commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
 usage eval(default('a','1','name','''Gonzo'''));
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
matrixlist_mean_std
optimise_B_given_A B_new = optimise_B_given_A(X,Wdata,A,lambda_B,force_B1,no_nans,blocks)
B_display
W_display [pos_TF,pos_operon] = W_display(W,method,options)
nca_display
export_to_tsv export_to_tsv(W,fields,headers,filename)
nca_network_statistics
sort_W_matrix [W,Wpicture,gene_order,TF_order] = sort_W_matrix(W)
sort_block
my_xticklabel
mytable result = mytable(names,rownumbers,filename)
rb_colors
traveling_salesman p = traveling_salesman(data,nit,method,seed)