Description of im
Home > nca > utils > im.m
im
PURPOSE
im(X,m,rownames,colnames)
SYNOPSIS
function im(X,m,rownames,colnames)
DESCRIPTION
 im(X,m,rownames,colnames)
CROSS-REFERENCE INFORMATION
This function calls:
rb_colors
This function is called by:
preprocess_gfp_data function [DD,info] = preprocess_gfp_data(D,parameters)
nca_loop [A_list,B_list] = nca_loop(...
optimise_W [W_new,A_new,X_pred,B,new,removed] = optimise_W(X,W_start,A,B,P,known_signs,sigma_0,p_sign_error,n_threshold_possible,n_iterations,graphics_flag,verbose);
D_display [GFP_p_OD,GFPder_p_OD,OD,GFP] = D_display(D,Wblock,graphics_flag)
W_display [pos_TF,pos_operon] = W_display(W,method,options)
display_multiple_curves display_multiple_curves(data)
nca_display