Description of label_names
Home > nca > utils > label_names.m
label_names
PURPOSE
function [label,indices] = label_names(names,allnames, method)
SYNOPSIS
function [label,indices] = label_names(names,allnames,method)
DESCRIPTION
 function [label,indices] = label_names(names,allnames, method)
 method 'multiple'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
check_signs
care_for_unmatched_genes Combine all data that form an identifiable network
combine_experiments D3 = combine_experiments(D1,D2)
gfp_data_determine_CV
gfp_data_unify_genes DD = gfp_data_unify_genes(D);
reorder_genes [W,D] = reorder_genes(operon_list,TF_list,W,D)
reorder_genes_W_D [W,D] = reorder_genes_W_D(gene_list,TF_list,W,D)
combine_networks [W1_new,W2_new,W_combined] = combine_networks(W1,W2,rename_list)
find_TF index = find_TF(TF,D)
find_gene
find_operon
nca_network_read_from_csv
nca_network_support determine those connections in network W that are in addition supported by network W_support
rearrange_W W_new = rearrange_W(W,gene_names,TF_names)
flatten_list takes a list of string lists and extracts all strings present