Description of mytable
Home > nca > utils > mytable.m
mytable
PURPOSE
result = mytable(names,rownumbers,filename)
SYNOPSIS
function res = mytable(names,rownumbers,filename)
DESCRIPTION
result = mytable(names,rownumbers,filename)
display cell array of strings to file
flag rownumbers: 0 (none), 1 (yes) ,'tex' (tex style)
(if filename is given -> output to file)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
entry_table
changes_table
export_to_tsv export_to_tsv(W,fields,headers,filename)
nca_network_statistics