Description of noticks
Home > nca > utils > noticks.m
noticks
PURPOSE
SYNOPSIS
function noticks();
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display_module_result
nca_display
plot_true_versus_fit plot_true_versus_fit(X,X_pred,W,indices,siz)
result_curves result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);