Description of subplot_n
Home > nca > utils > subplot_n.m
subplot_n
PURPOSE
SYNOPSIS
function [ni,nk]=subplot_n(N)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display_module_result
multiple_plot
multiple_plot_scatter
multiple_plot_two_curves multiple_plot_two_curves(B1,B2,s1,s2,names,B3,s3);
plot_true_versus_fit plot_true_versus_fit(X,X_pred,W,indices,siz)
result_curves result_curves(Wsub_block,operons_sub,TF_sub,X,A,TF_act,Xpred_sub);